# activemq default user for the webmanager is admin/admin
activemq:
  image: aterreno/activemq-dockerfile
  environment:
    - ACTIVEMQ_MIN_MEMORY="128"
    - ACTIVEMQ_MAX_MEMORY="256"
  ports:
    - 8161:8161
    - 61616:61616
#  expose:
#    - 61616