# activemq default user for the webmanager is admin/admin
activemq:
  image: aterreno/activemq-dockerfile
  environment:
    - ACTIVEMQ_MIN_MEMORY="128"
    - ACTIVEMQ_MAX_MEMORY="256"
  ports:
    - 8161:8161
  expose:
    - 61616

cms:
  image: cmsapplication/cmsapplication
  extra_hosts:
    - "output.service:127.0.0.1"
  ports:
    - 8080:8080

web:
  image: webapplication/webapplication
  extra_hosts:
    - "output.service:127.0.0.1"
  ports:
    - 8081:8080